services:
  - type: web
    name: iot-fastapi-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iot-db
          property: connectionString

databases:
  - name: iot-db
